apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: hm-grunndata-media-proxy
    team: teamdigihot
  name: valkey-teamdigihot-hm-grunndata-media-v1
  namespace: teamdigihot
spec:
  plan: startup-8
  project: nav-dev
  userConfig:
    valkey_maxmemory_policy: "allkeys-lru"
---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: teamdigihot
  name: valkey-teamdigihot-hm-grunndata-media-v1
  namespace: teamdigihot
spec:
  project: nav-dev
  destinationProjectName: nav-dev
  sourceProjectName: nav-dev
  integrationType: prometheus
  destinationEndpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733
  sourceServiceName: valkey-teamdigihot-hm-grunndata-media-v1