apiVersion: aiven.io/v1alpha1
kind: Valkey
metadata:
  labels:
    app: hm-grunndata-media-proxy
    team: teamdigihot
  name: valkey-teamdigihot-hm-grunndata-media-v1
  namespace: teamdigihot
spec:
  plan: startup-8
  project: nav-prod
  userConfig:
    valkey_maxmemory_policy: "allkeys-lru"
---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: teamdigihot
  name: valkey-teamdigihot-hm-grunndata-media-v1
  namespace: teamdigihot
spec:
  project: nav-prod
  destinationProjectName: nav-prod
  sourceProjectName: nav-prod
  integrationType: prometheus
  destinationEndpointId: 76685598-1048-4f56-b34a-9769ef747a92
  sourceServiceName: valkey-teamdigihot-hm-grunndata-media-v1