apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-media-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /imageproxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /imageproxy/internal/isReady
    initialDelay: 10
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /imageproxy/internal/prometheus
  env:
    - name: MEDIA_STORAGE_CDNURL
      value: "https://{{cdn_host}}/teamdigihot/grunndata/media/v1"
    - name: JAVA_OPTS
      value: "{{java_opts}}"
    - name: REDIS_HOST
      value: "hm-grunndata-media-redis"
    - name: LD_PRELOAD
      value: "/usr/lib/x86_64-linux-gnu/libjemalloc.so"
  gcp:
    sqlInstances:
      - name: hm-grunndata-media-proxy
        type: POSTGRES_15
        tier: {{ disk_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ disk_size }}
        diskAutoresize: true
        autoBackupTime: "03:00"
        databases:
          - name: mediaproxy
            envVarPrefix: DB
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-media-redis
      external:
        - host: "{{cdn_host}}"
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
