apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-media-proxy
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /imageproxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /imageproxy/internal/isReady
    initialDelay: 10
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 200m
      memory: 128Mi
  prometheus:
    enabled: true
    path: /imageproxy/internal/prometheus
  env:
    - name: MEDIA_STORAGE_CDNURL
      value: "{{ media_storage_cdnurl }}"
    - name: JDK_JAVA_OPTIONS
      value: "{{java_opts}}"
    - name: LD_PRELOAD
      value: "/usr/lib/x86_64-linux-gnu/libjemalloc.so"
    - name: REDIS_URI
      value: "rediss://${REDIS_USERNAME_HM_GRUNNDATA_MEDIA_V1}:${REDIS_PASSWORD_HM_GRUNNDATA_MEDIA_V1}@${REDIS_HOST_HM_GRUNNDATA_MEDIA_V1}:${REDIS_PORT_HM_GRUNNDATA_MEDIA_V1}"
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-media
      external:
        - host: "{{cdn_host}}"
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  valkey:
    - instance: hm-grunndata-media-v1
      access: readwrite