apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamdigihot
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: hm-grunndata-media-redis
  namespace: teamdigihot
spec:
  image: redis:7.0.11-alpine
  port: 6379
  command:
    - redis-server
    - "/redis-conf/redis.conf"
  filesFrom:
    - configmap: hm-grunndata-media-redis-config
      mountPath: /redis-conf
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      memory: 2166Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: hm-grunndata-media-proxy
        - application: hm-grunndata-redisexporter
