micronaut:
  server:
    port: ${SERVER_PORT:8080}
    context-path: "/imageproxy"
  application:
    name: hm-grunndata-media-proxy
    thread-selection: auto
  netty:
    event-loops:
      default:
        num-threads: 32
        prefer-native-transport: true
  metrics:
    enabled: true
    binders:
      cache:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true
      jvm:
        enabled: true
      web:
        enabled: true
      logback:
        enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  caches:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
  prometheus:
    sensitive: false
    enabled: true
  all:
    path: "/internal"

jackson:
  bean-introspection-module: true
  serialization:
    indentOutput: true

media:
  storage:
    cdnurl: ${MEDIA_STORAGE_CDNURL:`https://cdn.dev.nav.no/teamdigihot/grunndata/media/v1`}

redis:
  uri: ${REDIS_URI_hm-grunndata-media}
  caches:
    images:
      expire-after-write: 1d
    files:
      expire-after-write: 1d
  password: ${REDIS_PASSWORD_hm-grunndata-media}
  username: ${REDIS_USERNAME_hm-grunndata-media}

