apiVersion: aiven.io/v1alpha1
kind: Redis
metadata:
  labels:
    app: hm-grunndata-media-redis
    team: teamdigihot
  name: redis-teamdigihot-hm-grunndata-media
  namespace: teamdigihot
spec:
  plan: startup-8
  project: nav-dev
---
apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  labels:
    team: teamdigihot
  name: redis-teamdigihot-hm-grunndata-media
  namespace: teamdigihot
spec:
  project: nav-dev
  integrationType: prometheus
  destinationEndpointId: f20f5b48-18f4-4e2a-8e5f-4ab3edb19733
  sourceServiceName: redis-teamdigihot-hm-grunndata-media