name: "Redis v2: deploy to prod-gcp"

on: workflow_dispatch

jobs:
  deploy-redis:
    name: Deploy redis
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Redis
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/redis/redis-prod.yml
