name: "Redis v3: deploy to dev-gcp"

on: workflow_dispatch

jobs:
  deploy-redis:
    name: Deploy redis
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Redis
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/redis/redis-dev.yml
  deploy-redis-si:
    needs: deploy-redis
    name: Deploy redis serviceIntegration
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy Redis serviceIntegration
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/redis/redis-dev-si.yml

